# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
